### ISSUE TITLE
Fluent with Powercord

### ISSUE THREAD

**Issue by amineohn** [DiscordStyles/Fluent#1]
Hello, i have tried to install Fluent with Powercord it seems its not working with Discord Canary 110322 (392a1fa).

thanks again.

**Comment by Gibbu** [comment]
Correct the newest Cancary version has changed a lot of things. And won't be fixed until it comes to Stable.
Discord has a history of updating, reverting, updating, changing in span of a couple of hours to days.

It's pretty much a waste of time to actively support Canary.
