### ISSUE TITLE
[BUG]: Text private thread icon not displayed properly

### ISSUE THREAD

**Issue by Lisandra-dev** [DiscordStyles/Fluent#102]
### Describe the bug

The icon is a white square.

![image](https://github.com/DiscordStyles/Fluent/assets/30244939/bb4caef3-dab8-4de6-a979-917dda2b1e44)
VS
![image](https://github.com/DiscordStyles/Fluent/assets/30244939/71215790-6211-4e5d-9bac-84e33c24b429)

### To Reproduce

Install the theme

### Screenshots

![image](https://github.com/DiscordStyles/Fluent/assets/30244939/bb4caef3-dab8-4de6-a979-917dda2b1e44)
VS
![image](https://github.com/DiscordStyles/Fluent/assets/30244939/71215790-6211-4e5d-9bac-84e33c24b429)

### Infomation (please complete the following information)

**Discord channel**: _Stable/PTB/Canary_  Stable
**OS**: _Windows/Linux/OSX_  Windows
**Mod**: _BetterDiscord/Powercord/GooseMod_ BD 
**Discord language**: _Your language_ French

### Additional context

_Add any other context about the problem here. Remove if not applicable._

Installed using `@import url('https://discordstyles.github.io/Fluent/Icons.css');`

**Comment by Duve3** [comment]
This seems to be patched using @import

**Comment by Lisandra-dev** [comment]
Yes, I can confirm !
