### ISSUE TITLE
Bottom bar covers channels at the bottom

### ISSUE THREAD

**Issue by trungnt2910** [DiscordStyles/Fluent#103]
### Describe the bug

Bottom bar covers channels at the bottom. When the covered channel is the absolute last channel of a server, it is really hard to click on the link to access it because the user cannot scroll down any further.

### To Reproduce

- Install this theme.
- Join any server with a large number of channels.
- Try to access the last channel.

### Screenshots

_If applicable, add screenshots to help explain your problem_

![image](https://github.com/DiscordStyles/Fluent/assets/57174311/6677a9b0-f441-45c8-a4fc-0dbfef065335)

Bug is also visible on the sample image in the README.md file:

![image](https://github.com/DiscordStyles/Fluent/assets/57174311/c5a4b8f4-3264-46e6-8823-fcf632905125)

Whatever channel under the `SECRET` category is covered. In your case, it might be possible to scroll down, until you reach that server's last channel.

### Infomation (please complete the following information)

**Discord channel**: _**Stable**/~~PTB~~/~~Canary~~_  
**OS**: _**Windows**/~~Linux~~/~~OSX~~_  
**Mod**: _**BetterDiscord**/~~Powercord~~/~~GooseMod~~_  
**Discord language**: English

**Comment by Duve3** [comment]
I am unable to reproduce this bug. When I join big servers there is extra space at the bottom to allow me to scroll all the way down. I even tried to make a server with a bunch of channels, but there was always extra space at the bottom. I'm gonna assume that this was patched recently.

**Comment by trungnt2910** [comment]
Seems like this is specific to community servers using the [community onboarding](https://support.discord.com/hc/en-us/articles/11074987197975-Community-Onboarding-FAQ) feature.

All servers where I can reproduce this bug has a "Browse Channels" or "Channels & Roles" option at the top of the channel list.
For a normal non-community server I can see that there really is a big space at the bottom.

**Comment by Gibbu** [comment]
I've switched the bar to be static rather than floating so all of these issues shouldn't be a thing anymore.
