### ISSUE TITLE
The edit icon of the voice channel status is broken

### ISSUE THREAD

**Issue by xsm2** [DiscordStyles/Fluent#110]
### Describe the bug

The edit icon of the new voice channel estatus is broken

### To Reproduce

Enter a voice channel with the default estate

### Screenshots
Default theme
![imagen](https://github.com/DiscordStyles/Fluent/assets/32161135/5e7edc17-0aa1-43f3-a713-146e758f4505)

Fluent
![imagen](https://github.com/DiscordStyles/Fluent/assets/32161135/c2d78824-3e28-498a-93e1-6c93de960d47)

### Infomation (please complete the following information)

**Discord channel**: Stable
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: Spanish

**Comment by xsm2** [comment]
Fixed in my fork with this commit: https://github.com/xsm2/Fluent/commit/7132600cb726cfbe98ac74358a0b9b2a1790a1f7

**Comment by xsm2** [comment]
> Fixed in my fork with this commit: [xsm2@7132600](https://github.com/xsm2/Fluent/commit/7132600cb726cfbe98ac74358a0b9b2a1790a1f7)

This fix is currently broken because of discord's last update

**Comment by Gibbu** [comment]
Fixed.
