### ISSUE TITLE
Sounboard icon not visible

### ISSUE THREAD

**Issue by axxelet** [DiscordStyles/Fluent#111]
self explanatory, when joining a call its not visible, also make an icon for the translate modal 
![image](https://github.com/DiscordStyles/Fluent/assets/106402707/bc6d37e1-b543-44db-b4d1-91b105e617b5)

**Comment by shestak1996** [comment]
I have the same thing.

**Comment by shestak1996** [comment]
![image](https://github.com/DiscordStyles/Fluent/assets/95421989/e7d7c7dc-437f-4b93-8446-7de16eab80d3)
I had to figure it out and do this (return the icon default)

**Comment by Gibbu** [comment]
Not an issue anymore? I don't ever seeing this button.
