### ISSUE TITLE
Parts are unthemed

### ISSUE THREAD

**Issue by foursplaysroblox** [DiscordStyles/Fluent#113]
### Describe the bug

_A clear and concise description of what the bug is_
The title says it already
### To Reproduce

_Steps to reproduce the behavior_
boot up discord
### Screenshots

_If applicable, add screenshots to help explain your problem_
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/273722a5-a03e-45f1-b30a-32f34acdf262)
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/ca71e59a-101b-4e5c-a331-58aa9170aff2)
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/335de82e-007c-4d21-b4b2-6016befef031)
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/3a46f6d7-3692-40cb-b1ec-a42da7a85da3)
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/727cf111-a1bb-43c0-b87a-d64b57b8303e)
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/f2549d07-f115-487f-af13-071c67e28c6e)

### Infomation (please complete the following information)

**Discord channel**: PTB  
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English

### Additional context

_Add any other context about the problem here. Remove if not applicable._
none

**Comment by foursplaysroblox** [comment]
![image](https://github.com/DiscordStyles/Fluent/assets/82078139/2697bd18-afe9-48b1-b7c2-341bd7d09691)

**Comment by Gibbu** [comment]
Most of these are definitely fixed. I apologise if updates take longer than usual.
