### ISSUE TITLE
I need help to change voice and text channels fonts sizes

### ISSUE THREAD

**Issue by safaunal** [DiscordStyles/Fluent#115]
### I'm not too familiar with the coding. 
   I need help to change voice and text channels fonts.
   Which codes may i add to change these fonts sizes.

![Screenshot Fluen Discord Code](https://github.com/DiscordStyles/Fluent/assets/151393582/58b90f28-5963-4035-8987-c6a97ea6246e)

Thanks for helping.

**Discord channel**: _Stable
**OS**: _Windows 
**Mod**: _BetterDiscord
**Discord language**: _Turkish_

**Comment by Gibbu** [comment]
This isn't an issue with the theme but rather a general Discord question. Your best bet is to ask in the BetterDiscord discord server.
