### ISSUE TITLE
Horizontal server list support

### ISSUE THREAD

**Issue by bropines** [DiscordStyles/Fluent#117]
### Describe the bug

![image](https://github.com/DiscordStyles/Fluent/assets/57861007/f4ca8853-0635-481a-bc74-a6ec2b2f1bcc)

### To Reproduce

Enable HSL and Fluent

### Screenshots

![image](https://github.com/DiscordStyles/Fluent/assets/57861007/3e5a199c-de2e-416c-919a-3257ff1eec08)

### Infomation (please complete the following information)

**Discord channel**: _Stable_
**OS**: _Windows_  
**Mod**: _BetterDiscord_  
**Discord language**: _Russian_

**Comment by Gibbu** [comment]
I can't ever have full support unless BD gives me someway of detecting what themes are enabled at a given time.
I *could* make a snippet to "give" support though.
