### ISSUE TITLE
message bar is way too small on fluent

### ISSUE THREAD

**Issue by akirapink** [DiscordStyles/Fluent#118]
### Describe the bug
message bar is way too small on fluent

### To Reproduce
enable fluent

### Screenshots
![image](https://github.com/DiscordStyles/Fluent/assets/33667869/f420ccac-f1ab-458a-b339-8099716574cb)

### Infomation (please complete the following information)

**Discord channel**:  stable  
**OS**:  linux mint  
**Mod**: vencord
**Discord language**: british english

### Additional context

has to do with this classless div:
#app-mount > div.appAsidePanelWrapper__714a6 > div.notAppAsidePanel__9d124 > div.app_b1f720 > div > div.layers__1c917.layers_a23c37 > div > div > div > div > div.chat__52833 > div.content__1a4fe > div.container__93316 > div.chatContainer__23434 > main > form > div:nth-child(2)

**Comment by Gibbu** [comment]
Fixed
