### ISSUE TITLE
The icon size in the server list cannot be changed.

### ISSUE THREAD

**Issue by kreis117** [DiscordStyles/Fluent#123]
### Describe the bug

Changing the value of `--server-size` changes the width of the server list but not the icon size.

### To Reproduce

- 1. change the value of `:root` > `-server-size` in `https://raw.githubusercontent.com/DiscordStyles/Fluent/deploy/Fluent.theme.css` from `48px`.
- 2. change the width of the server list but not the icon size

### Screenshots

![image](https://github.com/DiscordStyles/Fluent/assets/74777259/6f3c526c-1183-48f1-ad39-f8956f58689b)

### Infomation (please complete the following information)

**Discord channel**: Canary
**OS**: Windows
**Mod**: OpenAsar
**Discord language**: Japanese

**Comment by Gibbu** [comment]
Yeah over the years Discord has changed many, many things. Leading up to maintaining this part of the theme really annoying to fix.
I've decided to remove it, sorry about that.
