### ISSUE TITLE
Icons in user's profile are misplaced

### ISSUE THREAD

**Issue by Biktol** [DiscordStyles/Fluent#124]
### Describe the bug

Icons like the HypeSquad, nitro subscription, etc are off.

### Screenshots

![imagen_2024-04-04_200440851](https://github.com/DiscordStyles/Fluent/assets/63794570/97da0a5b-ecbb-43c6-b6ee-eb452bff12e9)

### Infomation (please complete the following information)

**Discord channel**: Stable
**OS**: Windows 11
**Mod**: Vencord
**Discord language**: Spanish

**Comment by Gibbu** [comment]
I've reverted the user profiles back to default while I can figure out a good layout
