### ISSUE TITLE
Bad display of call actions buttons

### ISSUE THREAD

**Issue by Sinan-Karakaya** [DiscordStyles/Fluent#126]
### Describe the bug

The call actions buttons (screenshare, quit, mute...) lack padding, making them look bad and too small.

### To Reproduce

Join a call and look at the call screen.

### Screenshots

![image](https://github.com/DiscordStyles/Fluent/assets/91690021/1f34c294-f093-4bd2-84ab-58c387cab124)

### Infomation (please complete the following information)

**Discord channel**: Stable
**OS**: Windows
**Mod**: Vencord_  
**Discord language**: French

### Additional context

It looks like it could be fixed by changing the code from wrapper__4d4fe button__581d0 in _call.scss, by setting the padding to 24px, which works locally, but doesn't work when I try the deployed version.

**Comment by Gibbu** [comment]
Half fixed. This buttons are an absolute cluster fuck to fix.

**Comment by Sinan-Karakaya** [comment]
Just saw that, thanks
I tried to fix them myself, but oh how awful it is
