### ISSUE TITLE
Discord servers are square instead of round using Vencord

### ISSUE THREAD

**Issue by kegobass** [DiscordStyles/Fluent#128]
### Describe the bug

The Discord Servers are showing as square instead of round

### To Reproduce

  1.  Enable Fluent in Vencord themes online link
  2.  The Discord server icons are square, not round

### Screenshots

![2024-06-13_08-03](https://github.com/DiscordStyles/Fluent/assets/59669068/9e0f973f-f23d-486b-94bf-ad8c6633e0cc)
![2024-06-13_08-02](https://github.com/DiscordStyles/Fluent/assets/59669068/fb262355-1800-49bb-8c15-4129e9b48a31)

### Infomation (please complete the following information)

**Discord channel**:   Stable
**OS**:   Windows 11  
**Mod**:  Vencord
**Discord language**: English

### Additional context

This seems to have broken on the latest Discord update. It was working fine earlier this week,

Thanks!

**Comment by piotr25691** [comment]
yeah, also there's a problem with icons on those

the discord icon is supposed to be a home icon

**Comment by Gibbu** [comment]
Fixed.
