### ISSUE TITLE
Grave Accent acts as zero-width character in text area.

### ISSUE THREAD

**Issue by spectrapulse** [DiscordStyles/Fluent#15]
### Describe the bug
As title says, the Grave Accent or "backtick" is is acting as a zero-width character which makes using codeblocks hard and also makes it harder to format messages properly containing one or more of them.

In the case of a multi-line codeblock the tripple-grave's in the affixes stack ontop of each other making it even harder to use.

### To Reproduce  
Start formatting a message containing a single or multi-line codeblock.

### Screenshots
![image](https://user-images.githubusercontent.com/20131658/156393025-ee2f0d9b-9f08-44a8-aeb7-17336324cf42.png)
![NVIDIA_Share_9XH2B8ObhL](https://user-images.githubusercontent.com/20131658/156394242-c4706c62-6830-4c9b-8738-01cdff10b95d.gif)

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows 11*  
**Mod**: *Powercord*  
**Discord language**: *English (US)*

**Comment by Gibbu** [comment]
Yeah this seems to be a problem with the new font that is used. I might switch back to the original as this one doesn't allow bold fonts for some reason.
