### ISSUE TITLE
Role page empty

### ISSUE THREAD

**Issue by BestRazer** [DiscordStyles/Fluent#21]
### Describe the bug
Role page is empty

### To Reproduce  
1. Go to any of your own servers
2. Go to the server settings
3. Click on Roles

### Screenshots
![image](https://user-images.githubusercontent.com/65088083/159176398-0765f75e-15e0-44dd-b137-c1130651d10b.png)
### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *German*

**Comment by Gibbu** [comment]
This is fixed in the latest updated.
