### ISSUE TITLE
Channel with threads did not display correctly in the side tab

### ISSUE THREAD

**Issue by Eschatologue** [DiscordStyles/Fluent#24]
### Describe the bug
Channel with threads did not display correctly in the side tab

### To Reproduce  
Click a channel with a thread

### Screenshots
![image](https://user-images.githubusercontent.com/65104201/159836957-74682161-e5b6-4355-a852-4cc2a0577ced.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *GooseMod*  
**Discord language**: *English*

**Comment by cfpwastaken** [comment]
This is on Linux with BetterDiscord too.
