### ISSUE TITLE
Search window

### ISSUE THREAD

**Issue by Origin9115** [DiscordStyles/Fluent#25]
### Describe the bug
*Search window that called find or start a conversation*

### To Reproduce  
*you literally forgot to customize this or maybe it's a bug 👍*  

### Screenshots
*If applicable, add screenshots to help explain your problem*
![Screenshot_102](https://user-images.githubusercontent.com/54654816/159862073-04505bfc-52da-40f4-8c16-d0f9ff5ac6e3.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Fixed.
