### ISSUE TITLE
Channel icons seem to be too small 2560x1440

### ISSUE THREAD

**Issue by Larsy93** [DiscordStyles/Fluent#30]
### Describe the bug
Channel icons seem to be too small 2560x1440

### Screenshots
https://i.gyazo.com/09aed731e82c0225c78cebc622281b1d.png

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by Larsy93** [comment]
maybe not a problem, just takes getting used to, or make it toggleable if its easy via config.

**Comment by Gibbu** [comment]
There's currently 3 variables that you can "change", to some extent.
```
	--server-icon-size: 28px;
	--server-size: calc(var(--server-icon-size) + 16px);
	--server-width: 64px;
```
But those have their limits. Tomorrow I'll take another shot at adding an easier way of increasing the server avatar/size.

**Comment by Gibbu** [comment]
Good news! I've added a `--server-size` variable includes into the `Fluent.theme.css`.

This will increase the server size and auto increase the server icon image if not manually changed.
