### ISSUE TITLE
Server settings problem

### ISSUE THREAD

**Issue by JustSomeRandomGuy3** [DiscordStyles/Fluent#31]
### Describe the bug
Can't add role/member for a channel, roles part in server settings and channel settings are unthemed

### Screenshots
![image](https://user-images.githubusercontent.com/102457568/160270521-40b8b57f-fec3-4ebc-a0d5-e4caee256968.png)
![image](https://user-images.githubusercontent.com/102457568/160270765-2ca22e38-c67b-45fb-8503-df978a222ead.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows 10*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by maicol07** [comment]
@Gibbu the permissions bug is still there in 1.0.3
