### ISSUE TITLE
Message with header right click bug

### ISSUE THREAD

**Issue by xsm2** [DiscordStyles/Fluent#33]
### Describe the bug
The title is pretty confusing, but the bug pretty easy to spot. When you right-click a message with header (a message with the name of the author, the first one in a batch of messages by the same person), the the message container change it's width to ocupy the 100% of the available space. This behaviour does NOT happen when the message doesn't have a header.

### To Reproduce  
Right click in a message with header

### Screenshots
Normal message:
![imagen](https://user-images.githubusercontent.com/32161135/160607083-f467f6a0-65fd-4286-8151-442ab132d4b2.png)
Right clicked:
![imagen](https://user-images.githubusercontent.com/32161135/160606989-d85bdfb6-435d-4c97-bc95-11d5658b0562.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *Spanish*  

### Additional context
*Add any other context about the problem here. Remove if not applicable.*

**Comment by Gibbu** [comment]
Known and cannot fix. Discord uses the same class for right clicking a message and editing a message.

**Comment by xsm2** [comment]
Hey, I know that this closed (more than closed lol), but I have been recently making changes in my fork and I have basically fixed this by changing the style of the edit message so that it doesn't use 100% of the horizontal space.

![imagen](https://github.com/DiscordStyles/Fluent/assets/32161135/a88c0836-6862-4a79-b69e-1ba5317157c5)

The code to do this is this:

https://github.com/xsm2/Fluent/blob/03747f1f00350fedc74e6f81b754a3551ec02152/src/theme/chat/_message.scss#LL24C1-L24C38

https://github.com/xsm2/Fluent/blob/03747f1f00350fedc74e6f81b754a3551ec02152/src/theme/chat/_message.scss#L205-L251C2

I know the quality of the code is not specially goog but it works, if you like it feel free to copy or change whatever you want
