### ISSUE TITLE
Goosemod setting buttons have no icons.

### ISSUE THREAD

**Issue by RealTriassic** [DiscordStyles/Fluent#37]
### Describe the bug
The buttons added to settings by Goosemod have no icons next to them, even though the modification is supported by Fluent.

### To Reproduce
Inject Goosemod into Discord, download the Fluent theme from the theme store and open the settings.

### Screenshots
<img width="167" alt="image" src="https://user-images.githubusercontent.com/40073455/161496234-d2c14820-a939-4c82-a5cf-2e9107c12f38.png">

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *GooseMod*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
I personally don't use GM, a PR if possible would be appreciated.

**Comment by maicol07** [comment]
I have the same issue with BetterDiscord:

![](https://user-images.githubusercontent.com/9463142/164208668-106a3a8f-8dd2-421d-b21c-48724d8f8a4c.png)

**Comment by Gibbu** [comment]
Since Discord decided to remove the `aria-controls` on non-active items. I'm going to be disabling icons.
