### ISSUE TITLE
Cant close welcome popup

### ISSUE THREAD

**Issue by decoder0007** [DiscordStyles/Fluent#40]
### Describe the bug
On the powercord popup when installing you cant get off the menu

### To Reproduce  
install powercord and then the theme before starting

### Screenshot
![image](https://user-images.githubusercontent.com/50407945/162621379-2bc689eb-a33a-4dac-ad96-4d7fdedcbb77.png)

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Closed since Powercord is dead.

**Comment by decoder0007** [comment]
Rip
