### ISSUE TITLE
Icons Are Blurry

### ISSUE THREAD

**Issue by Caffeine-js** [DiscordStyles/Fluent#49]
All The Icons Are Blurred In The Fluent Theme, Including The Server Icons And The Setting Icons As Well.

<img width="23" alt="image" src="https://user-images.githubusercontent.com/99310713/165136372-440fa3d6-76e0-4c71-999b-3b20892788f5.png">

### Infomation (please complete the following information)
**Discord channel**: Stable
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English

**Comment by Gibbu** [comment]
The icons you screenshot are expected to be blurry as they're just PNGs set to a 18x18 resolution.
The server icons and such being blurring should only become noticeable if you've increased the server size above default Discord.

I *could* increase the size of the image but keep them to 18x18 but then people that aren't using a zoomed in Discord would view them as blurry.

**Comment by Gibbu** [comment]
Closing since Discord remove any reliable way to add icons.
