### ISSUE TITLE
Welcome modal not displaying verification tick

### ISSUE THREAD

**Issue by GlitchedTwitchTV** [DiscordStyles/Fluent#50]
### Describe the bug
*A clear and concise description of what the bug is*  
when trying to complete the verification thing as such in gibbus support server, whilst using the fluent theme, you cannot see the tick box for verification
### To Reproduce  
*Steps to reproduce the behavior*  
N/A it just happened when trying to verify on gibbus support server
### Screenshots
*If applicable, add screenshots to help explain your problem*
![image_2022-04-25_180414029](https://user-images.githubusercontent.com/104382184/165138198-cd032ccc-9ddb-49e0-b2df-d0a034e92ab8.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable/PTB/Canary*  
stable
**OS**: *Windows/Linux/OSX* 
windows (11)
**Mod**: *BetterDiscord/Powercord/GooseMod* 
Better Discord 
**Discord language**: *Your language*  
English (uk)

### Additional context
*Add any other context about the problem here. Remove if not applicable.*

**Comment by Gibbu** [comment]
Not quite sure how to trigger this.
