### ISSUE TITLE
Border around image modal

### ISSUE THREAD

**Issue by GlitchedTwitchTV** [DiscordStyles/Fluent#51]
### Describe the bug
*A clear and concise description of what the bug is*  
screenshots or images, when too long, seem to go off of the side of the screen when clicked and shown in big picture, sometimes making half of the text unreadable etc. 
and smaller screenshots have a horrible long box outline when shown in big picture. (same for other pictures too, outline is visible
### To Reproduce  
*Steps to reproduce the behavior*  
take a long vertical screenshot, post and click it, same for the smaller and other screenshots
### Screenshots
*If applicable, add screenshots to help explain your problem*
![image_2022-04-25_180909853](https://user-images.githubusercontent.com/104382184/165138933-295c782c-2036-4a4b-9d52-9e469da98ac6.png)
![image_2022-04-25_180923043](https://user-images.githubusercontent.com/104382184/165138962-645e65ad-7c8c-4ab0-b57b-7c6feed50479.png)
![image_2022-04-25_181000122](https://user-images.githubusercontent.com/104382184/165139050-98c841cf-be21-4eaa-b511-0879b456903e.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable/PTB/Canary*  
stable
**OS**: *Windows/Linux/OSX*  
windows (11)
**Mod**: *BetterDiscord/Powercord/GooseMod*  
BetterDiscord
**Discord language**: *Your language*  
English (uk)

### Additional context
*Add any other context about the problem here. Remove if not applicable.*

**Comment by Gibbu** [comment]
This is because of your plugin.
