### ISSUE TITLE
When typing a large message a bar appears

### ISSUE THREAD

**Issue by keatit71** [DiscordStyles/Fluent#52]
### Describe the bug
A bar appears so that large messages can be displayed but never goes away

### To Reproduce  
enable fluent and type or paste a large message then delete or send it

### Screenshots
![Discord_68MohdlE68](https://user-images.githubusercontent.com/42551576/165147385-a042f67c-2ec2-4fd8-a1c8-242ca4a8910d.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable  
**OS**: *Windows
**Mod**: *BetterDiscord
**Discord language**: English

**Comment by Gibbu** [comment]
You mistaken [Fluent Discord](https://github.com/TakosThings/Fluent-Discord) for Fluent.
