### ISSUE TITLE
Sidebar freezes when scrolling (cannot select channels)

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [DiscordStyles/Fluent#56]
As per the title. The sidebar containing the channels often freezes, being unable to scroll nor select any channels to open. This usually occurs when scrolling through the list quickly, and happens on both trackpad and mouse.

One way to fix it is to change to a different server then back (but this is clearly not great). Another way seems to be resizing the app.

**Comment by Gibbu** [comment]
And there's not much I can do about this. Even slightly changing the channels list will cause Discord's lazy loading to bug out.
It can even happen with default Discord.
