### ISSUE TITLE
Channel List Freeze

### ISSUE THREAD

**Issue by Kweeme** [DiscordStyles/Fluent#59]
### Describe the bug
The channel list will freeze up if you go to the bottom of a server's channel list. 

### To Reproduce  
Scroll to the bottom of a server's channel list.

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Linux*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

### Additional context
*Add any other context about the problem here. Remove if not applicable.*

**Comment by Gibbu** [comment]
Read #56.
