### ISSUE TITLE
Do you think it looks big in 100% scaling?

### ISSUE THREAD

**Issue by HuyHung1408** [DiscordStyles/Fluent#6]
![image](https://user-images.githubusercontent.com/86362423/155142806-e70ae348-eda2-44f9-821d-4b2202f527bb.png)

**Comment by Gibbu** [comment]
You can change pretty much all of that with variables.
There are two variables inside of `Fluent.theme.css` which control the channels/member lists.

And you've got these to mess around with: <https://github.com/DiscordStyles/Fluent/blob/main/src/_root.scss>
Just copy the variables to the `:root` of your `Fluent.theme.css`.

I seem to forgot to add the chat bubble variables which will allow you to reduce padding, margin and background colour.

**Comment by HuyHung1408** [comment]
Ah, seems like it was good now, thanks. I have no suggestions for now because this is the best Fluent theme for Discord already! Have a nice day!
