### ISSUE TITLE
User Popout is not consistent.

### ISSUE THREAD

**Issue by TheDarkKnight69** [DiscordStyles/Fluent#60]
The user popout at the bottom is a rectangular box rather than a circular one. Maybe fix this?

![image](https://user-images.githubusercontent.com/91176991/167804920-854b969a-54ee-4c6a-a459-61d4ebd3d9d0.png)

**Comment by Gibbu** [comment]
I will fix it once Discord decides to give me the update.

**Comment by TheDarkKnight69** [comment]
okay thank you

**Comment by TheDarkKnight69** [comment]
Did you fix it yet?
