### ISSUE TITLE
Suggestion: Make bars under search bars animated. 

### ISSUE THREAD

**Issue by Kiyoshi-23** [DiscordStyles/Fluent#61]
This is just a suggestion so i'm not really expecting a response to this but i'll go ahead and say it anyways. 
In order to make it a more comfy look and feeling, you should make the search bars in the theme animated. What i'm saying is that when it is clicked, the blue line under it can slide out to either side, instead of it just appearing. I feel that many people will like this new feature and that it will make the theme just a tad bit better. 

This can be done with a simple addition of css code. 

![Screen Shot 2022-05-16 at 5 14 47 PM](https://user-images.githubusercontent.com/90008981/168691134-98b74ec1-2cd8-4234-bea0-958cba280ce5.png)

Here is another example of what I was talking about: https://stackoverflow.com/questions/46887024/underline-animation-on-click

Let me know if you do agree to this.

**Comment by Gibbu** [comment]
While it would look nice, it's not part of the Fluent UI design system.
So it won't be added.

**Comment by Kiyoshi-23** [comment]
Oh ok, No problem.

I have the code for this.. you can dm me for it if you change your mind. Kiyoshi#5246
