### ISSUE TITLE
Top bar is overlapping

### ISSUE THREAD

**Issue by sfarmani** [DiscordStyles/Fluent#62]
### Describe the bug
The top bar is overlapping everything else at the top - this just happened today
It might have been because a new discord update?

### To Reproduce  
Launch Discord with Fluent installed

### Screenshots
![image](https://user-images.githubusercontent.com/15093212/168913723-99d79bef-a711-41ec-9d1c-5b53cc91a3d7.png)

### Infomation (please complete the following information)
**Discord channel**: Canary
**OS**: Windows 11
**Mod**: Powercord 
**Discord language**: English

**Comment by hahagu** [comment]
Can confirm the same issue.
Windows 11, GooseMod, Stable

**Comment by ritokatsuga** [comment]
I would like to confirm the same issue here.
I'm on Windows 11 21H2, GooseMod, stable channel
![image](https://user-images.githubusercontent.com/35857106/168969859-443a7e9d-5203-4818-bb94-7dbdf8a3116b.png)

**Comment by Kasper-Who** [comment]
Same issue, I'm assuming the latest discord update scuffed it?

![Discord_oWyp9kY1nF](https://user-images.githubusercontent.com/12468784/168989862-10959506-bf84-4307-a6db-564599f0a6d2.png)

Windows 10
Better Discord
Stable
English
