### ISSUE TITLE
Top of window cut off

### ISSUE THREAD

**Issue by hahagu** [DiscordStyles/Fluent#64]
Same issue as #62 

Windows 11
Discord Stable
GooseMod

![image](https://user-images.githubusercontent.com/3746349/169636821-7f331999-4b47-451f-aff2-2e44d7c303cc.png)

**Comment by sfarmani** [comment]
Same thing with me, I saw an update to discord canary yesterday that might have borked it again lol

![image](https://user-images.githubusercontent.com/15093212/169662799-eba047d6-0343-4c89-8d31-0e99ba6dcfcd.png)
windows 11
powercord

**Comment by ritokatsuga** [comment]
#62 It happens again with the same condition, and usually happens whenever I restarted my client using Ctrl+R command

**Comment by Gibbu** [comment]
Discord being Discord and decided to add a container and then later remove it.🤦
