### ISSUE TITLE
The top of the discord title bar is cut off.

### ISSUE THREAD

**Issue by TheDarkKnight69** [DiscordStyles/Fluent#67]
### Describe the bug
The top of the Discord Title bar is partly cutoff. 

### To Reproduce  
Download latest version of Fluent and you get this problem

### Screenshots
![image](https://user-images.githubusercontent.com/91176991/171792050-90458d3c-101d-4815-a94b-7d9207faccde.png)

### Infomation (please complete the following information)
**Discord channel**: Canary  
**OS**: *Windows
**Mod**: *BetterDiscord
**Discord language**: English

**Comment by Gibbu** [comment]
I cannot reproduce.
![image](https://user-images.githubusercontent.com/20338746/171796378-608e33a7-9b9c-4704-b19e-5a9a9a043374.png)

Do you have any other themes/customcss enabled?

**Comment by ritokatsuga** [comment]
![image](https://user-images.githubusercontent.com/35857106/171952871-7e389662-639f-4e98-ba8a-909c6fab9431.png)
Partially cut off again. Same issue like #62 and #64 with the same config: Stable, Goosemod, Windows 11 21H2

**Comment by BoardSodie** [comment]
I am having the same issue.
![image](https://user-images.githubusercontent.com/70685547/171977609-69a988e5-c5cc-4027-b56f-f001381796d5.png)

**Comment by Tostware-yt** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/81415735/171992148-4ac45da3-fde2-4408-957e-eab65ae40c10.png">
same
