### ISSUE TITLE
Newest update broke the theme?

### ISSUE THREAD

**Issue by sfarmani** [DiscordStyles/Fluent#68]
### Describe the bug
I recently updated to [v1.0.8](https://github.com/DiscordStyles/Fluent/commit/35940e11eb11042f19c8ac732fe318f2afe63af5)
all was good, until I restarted discord, the theme was no longer applied... Could this be due to the Fluent.theme.css file no longer being present in the /dist directory?

### To Reproduce  
Updated Fluent theme
Restart Discord

### Information (please complete the following information)
**Discord channel**: Canary
**OS**: Windows 11  
**Mod**: Powercord  
**Discord language**: English

**Comment by Gibbu** [comment]
Whoops, I forgot to switch the Powercord manifest to target the new file.

**Comment by Gibbu** [comment]
Fixed.

**Comment by sfarmani** [comment]
Sorry if I am re-opening this

I am not sure if that fixed it. I got a fresh install of the theme on powercord and it still didn't apply the theme...

**Comment by Gibbu** [comment]
Yeah, I *SOMEHOW* forgot to actually change the `powercord_manifest.json`... 😮‍💨
