### ISSUE TITLE
Theme not being applied again

### ISSUE THREAD

**Issue by sfarmani** [DiscordStyles/Fluent#74]
### Describe the bug
When opening discord today, the theme was no longer applied

The last change to `powercord_manifest.json` in [this commit](https://github.com/DiscordStyles/Fluent/commit/c826263de7720455206a0403136165ce6a5ba9c5) seems to have messed up theme application to discord

As I recall, [a couple of changes ago](https://github.com/DiscordStyles/Fluent/commit/35940e11eb11042f19c8ac732fe318f2afe63af5), the `Fluent.theme.css` file was trashed

I am able to temp fix this by updating the manifestjson file back to what it was in the latest commit

### To Reproduce  
1. Update the theme
2. Full restart discord

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows 11*  
**Mod**: *Powercord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Reclone the repo but target the deploy branch.

As said in the README:
![image](https://user-images.githubusercontent.com/20338746/175804364-f771dbe1-d034-4dc1-bcb2-e720e108ba93.png)

**Comment by sfarmani** [comment]
Thanks! I wasn't aware of that
