### ISSUE TITLE
Missing Connections icon

### ISSUE THREAD

**Issue by emigdio821** [DiscordStyles/Fluent#77]
Hi Gibbu, could you please add an icon for this section? thanks in advance, below you can find an screenshot.

### Screenshots
![image](https://user-images.githubusercontent.com/6751108/185284572-24884fc7-f4f7-426c-8010-a85db142793a.png)

### Infomation
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English* 

###  Additional comments
Is it possible to use the default discord font?
I tried adding CSS variables but it did not work
```
--font-display: inherit;
--font-primary: inherit; 
```

**Comment by Gibbu** [comment]
Closing since Discord remove any reliable way to add icons.
