### ISSUE TITLE
new inbox button position and game activity toggle plugin broken

### ISSUE THREAD

**Issue by diyachan** [DiscordStyles/Fluent#8]
not sure is this starting to rolling to more people but recently Discord tested out a new location for Inbox from the toolbar to the button on top of the home button

![image](https://user-images.githubusercontent.com/7719971/155720153-f34a1a3d-4adf-4172-9d13-2b431d6feba5.png)

game activity toggle plugin (BD) is also broken at the moment

![image](https://user-images.githubusercontent.com/7719971/155720502-1bed6bf3-ce65-40a1-be50-68528a302623.png)

Discord Stable, downloaded the theme from GooseMod store

**Comment by Gibbu** [comment]
There's no way that's going to be the new location for the inbox. Discord must be out of their mind.

I'll take a look at the Activity button later today.
