### ISSUE TITLE
Bottom left corner user popout has the avatar covering the name

### ISSUE THREAD

**Issue by trungnt2910** [DiscordStyles/Fluent#86]
### Describe the bug
*A clear and concise description of what the bug is*  
Bottom left corner user popout has the avatar covering the name

### To Reproduce  
*Steps to reproduce the behavior*  

- Install this theme.
- Click on the icon at the bottom left of the chat area.

### Screenshots
*If applicable, add screenshots to help explain your problem*

![image](https://user-images.githubusercontent.com/57174311/192758499-783232aa-ad65-4df4-987a-e5aed1866ea5.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

### Additional context
*Add any other context about the problem here. Remove if not applicable.*  

When #83 was merged, the problem did not exist.

The problem did not exist on my device until late afternoon today so I guess it's related to 1ff92d3931935be41a5a79ef0c823841206c912b.

**Comment by Gibbu** [comment]
Mine doesn't even look like yours.
![Discord_i9iP4UJNIA](https://user-images.githubusercontent.com/20338746/192767463-94a28dfc-2a8c-43f8-b001-0956c3b8db80.png)

**Comment by Gibbu** [comment]
And https://github.com/DiscordStyles/Fluent/commit/1ff92d3931935be41a5a79ef0c823841206c912b shouldn't have caused the issue since all the css is scoped to the user modal?
But I also don't wanna touch user popouts/modals for now since in the last week Discord has changed them about 5 times already.

**Comment by trungnt2910** [comment]
Strange, I haven't updated Discord and/or install any new themes/plugins today, the problem just suddenly shows up.

**Comment by Gibbu** [comment]
*Finally* fixed.
