### ISSUE TITLE
Self Message and Icons (from screenshot settings) not showing

### ISSUE THREAD

**Issue by itoffie** [DiscordStyles/Fluent#87]
>>>> https://discordstyles.github.io/Fluent/SelfMessages.css <<<<

doesnt work as seen here 
![image](https://user-images.githubusercontent.com/64309702/193324233-cf014c63-1717-46bd-af31-b399a4777748.png)

and as for the icons
as you can see here i just imported DevilBro's DiscordRecolor SettingsIcons css since Fluent doesnt work 
![image](https://user-images.githubusercontent.com/64309702/193323560-dec8fb2d-272d-4c96-b3ae-f85154703ee1.png)

**Discord channel**: Stable
**OS**: Windows 7
**Mod**: BetterDiscord
**Discord language**: English US

**Comment by Gibbu** [comment]
This is because self messages require DevilBro plugin library. Which to my knowledge isn't working right now because of the major Discord update.

**Comment by itoffie** [comment]
is it possible to do adjustments on the theme? like making a profile icon and not using avatar next to mute/unmute instead of the current profile profile avatar next to chat box
![image](https://user-images.githubusercontent.com/64309702/193379856-adbe66ec-af4f-46ba-9990-13ada7a6e558.png)


then moving the attach/create thread/slash command button to the right side of the message box or next to emoji/sticker/gif/gift icons
![image](https://user-images.githubusercontent.com/64309702/193379877-cd7798bc-05b5-4965-847b-3234d92cb97d.png)

there's also this 
-avatar+nickname overlap issue
-status icon not next to status switcher
-account switch icon (else if there's no plan on adding icons on status and account switcher align them with the Set Custom Status, sorry about my little adjustment requests)
![image](https://user-images.githubusercontent.com/64309702/193379962-500a2aba-9007-4057-b3e0-d55a1a1ca097.png)

**Comment by itoffie** [comment]
![image](https://user-images.githubusercontent.com/64309702/193408607-8e98a553-b5c4-4f9f-a6c2-8ec7f6b44025.png)
as i just noticed now... profile button still showing while viewing forum threads

**Comment by itoffie** [comment]
closed since the profile moved back to server list
