### ISSUE TITLE
(Question) A version containing only icons

### ISSUE THREAD

**Issue by KristalAndStarlight** [DiscordStyles/Fluent#90]
This theme is good, maybe not for everyone, but like the icons.. the ICONS are AMAZING. So, I think it would be nice if a version was compiled that only changes the icons.

**Comment by Gibbu** [comment]
Should be easy enough

**Comment by Duve3** [comment]
> This theme is good, maybe not for everyone, but like the icons.. the ICONS are AMAZING. So, I think it would be nice if a version was compiled that only changes the icons.

If you want to use just the icons, at least in BetterDiscord, you can just do ```@import url('https://discordstyles.github.io/Fluent/Icons.css');``` inside of custom CSS. But you can most likely also do this inside of any theme.

**Comment by Duve3** [comment]
can someone please close this issue as it has been solved.
