### ISSUE TITLE
Edit message's Emoji picker it's empty

### ISSUE THREAD

**Issue by xsm2** [DiscordStyles/Fluent#97]
### Describe the bug

Edit message's Emoji picker doesn0t work, while the regular one works fine.

### To Reproduce

Edit a message and click in the smiley face icon

### Screenshots

![imagen](https://github.com/DiscordStyles/Fluent/assets/32161135/8664c6de-7fd2-4160-b3ac-993a07e36e54)

### Infomation (please complete the following information)

**Discord channel**: _Stable_
**OS**: _Windows_  
**Mod**: _BetterDiscord_  
**Discord language**: _Spanish_

**Comment by xsm2** [comment]
Fixed in my fork with this commit: https://github.com/xsm2/Fluent/commit/7e991c137f85140a0c210864bab455e5a1ff97b3

**Comment by Gibbu** [comment]
Fixed.
